package com.a2zinvoices.app;
import android.os.*;import android.app.*;import android.view.*;import android.widget.*;import android.graphics.Color;import java.util.*;
public class InvoiceActivity extends BaseActivity{
 EditText num,cname,cact,caddr,ccr,ctax,vat,stamp;Spinner customers,products,payment;LinearLayout lines,totals;ArrayList<InvoiceLine> rows=new ArrayList<>();TextView sub,va,grand;String date;
 public void onCreate(Bundle b){super.onCreate(b);setup("تحرير فاتورة");date=new java.text.SimpleDateFormat("dd/MM/yyyy",Locale.US).format(new Date());
  num=field("رقم الفاتورة");num.setText(DataStore.nextInvoiceNumber());TextView dt=tv("التاريخ: "+date);root.addView(dt);
  customers=new Spinner(this);ArrayList<String> cs=new ArrayList<>();cs.add("اختر الزبون");for(Customer c:DataStore.customers)cs.add(c.name);customers.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,cs));root.addView(customers);customers.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){if(pos>0){Customer c=DataStore.customers.get(pos-1);cname.setText(c.name);cact.setText(c.activity);caddr.setText(c.address);ccr.setText(c.commercialRegister);ctax.setText(c.taxId);}}});
  cname=field("اسم الزبون *");cact=field("النشاط");caddr=field("العنوان");ccr=field("رقم السجل التجاري");ctax=field("الرقم الجبائي");
  products=new Spinner(this);ArrayList<String> ps=new ArrayList<>();ps.add("اختر سلعة من المخزون");for(Product p:DataStore.products)ps.add(p.name);products.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ps));root.addView(products);
  button("➕ إضافة سطر من المخزون",v->addStock());button("➕ سطر يدوي",v->addManual());lines=new LinearLayout(this);lines.setOrientation(LinearLayout.VERTICAL);root.addView(lines);
  vat=field("نسبة الرسم %");vat.setText("17");stamp=field("الطابع الجبائي");stamp.setText("0");
  payment=new Spinner(this);String[] pm={"نقدا","شيك","تحويل بنكي","أجل"};payment.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,pm));root.addView(payment);
  sub=tv("المجموع بدون رسوم: 0.00 د.ج");va=tv("القيمة المضافة: 0.00 د.ج");grand=tv("المجموع الكلي: 0.00 د.ج");root.addView(sub);root.addView(va);root.addView(grand);
  button("💾 حفظ الفاتورة",v->save(false));button("🖨 معاينة/فتح PDF",v->save(true));button("إلغاء",v->finish());
 }
 TextView tv(String s){return super.tv(s,16);}
 void addStock(){int p=products.getSelectedItemPosition()-1;if(p<0){msg("الرجاء اختيار سلعة من القائمة أولاً.");return;}Product x=DataStore.products.get(p);InvoiceLine l=new InvoiceLine();l.productId=x.id;l.productName=x.name;l.unit=x.unit;l.quantity=1;l.unitPrice=x.unitPrice;rows.add(l);drawRows();}
 void addManual(){InvoiceLine l=new InvoiceLine();l.productName="سلعة جديدة";l.unit="قطعة";rows.add(l);drawRows();}
 EditText ed(String val){EditText e=new EditText(this);e.setText(val);e.setSingleLine();e.setTextSize(14);e.setGravity(Gravity.RIGHT);return e;}
 void drawRows(){lines.removeAllViews();for(int i=0;i<rows.size();i++){final int k=i;InvoiceLine l=rows.get(i);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(6,10,6,10);box.setBackgroundColor(Color.WHITE);TextView h=new TextView(this);h.setText("السطر "+(i+1));box.addView(h);EditText pn=ed(l.productName);pn.setHint("التعيين");box.addView(pn);EditText un=ed(l.unit);un.setHint("الوحدة");box.addView(un);EditText q=ed(String.valueOf(l.quantity));q.setHint("الكمية");box.addView(q);EditText pr=ed(String.valueOf(l.unitPrice));pr.setHint("سعر الوحدة");box.addView(pr);Button del=new Button(this);del.setText("🗑 حذف السطر");box.addView(del);del.setOnClickListener(v->{rows.remove(k);drawRows();});TextView total=new TextView(this);total.setText("المجموع: "+l.total()+" د.ج");box.addView(total);TextWatcherImpl w=new TextWatcherImpl(l,pn,un,q,pr,total);pn.addTextChangedListener(w);un.addTextChangedListener(w);q.addTextChangedListener(w);pr.addTextChangedListener(w);lines.addView(box);}calc();}
 class TextWatcherImpl implements android.text.TextWatcher{InvoiceLine l;EditText pn,un,q,pr;TextView t;TextWatcherImpl(InvoiceLine l,EditText a,EditText b,EditText c,EditText d,TextView t){this.l=l;pn=a;un=b;q=c;pr=d;this.t=t;}public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){l.productName=pn.getText().toString();l.unit=un.getText().toString();l.quantity=num(q.getText().toString());l.unitPrice=num(pr.getText().toString());t.setText("المجموع: "+l.total()+" د.ج");calc();}public void afterTextChanged(android.text.Editable e){}}
 double num(String s){try{return Double.parseDouble(s.replace(',','.'));}catch(Exception e){return 0;}}
 void calc(){double st=0;for(InvoiceLine l:rows)st+=l.total();double vr=num(vat==null?"17":vat.getText().toString()),fs=num(stamp==null?"0":stamp.getText().toString());double v=Math.round(st*vr*100.0/100.0)/100.0,g=Math.round((st+v+fs)*100)/100.0;if(sub!=null){sub.setText("المجموع بدون رسوم: "+String.format(Locale.US,"%.2f",st)+" د.ج");va.setText("القيمة المضافة: "+String.format(Locale.US,"%.2f",v)+" د.ج");grand.setText("المجموع الكلي: "+String.format(Locale.US,"%.2f",g)+" د.ج");}}
 Invoice make(){Invoice i=new Invoice();if(cname.getText().toString().trim().isEmpty()){msg("الرجاء إدخال اسم الزبون أو اختياره.");return null;}if(rows.isEmpty()){msg("الرجاء إضافة سطر واحد على الأقل.");return null;}i.number=num.getText().toString().trim();i.date=date;i.customerName=cname.getText().toString().trim();i.customerActivity=cact.getText().toString().trim();i.customerAddress=caddr.getText().toString().trim();i.customerCommercialRegister=ccr.getText().toString().trim();i.customerTaxId=ctax.getText().toString().trim();i.vatRate=num(vat.getText().toString());i.fiscalStamp=num(stamp.getText().toString());i.paymentMethod=payment.getSelectedItem().toString();i.lines.addAll(rows);return i;}
 void save(boolean pdf){Invoice i=make();if(i==null)return;DataStore.invoices.add(i);DataStore.saveInvoices();if(pdf)try{PdfHelper.open(this,PdfHelper.create(this,i,DataStore.company));}catch(Exception e){msg("تعذر إنشاء PDF: "+e.getMessage());}else{msg("تم حفظ الفاتورة بنجاح.");finish();}}
}